config/routes.rb
FishTaggerFrontFacing::Application.routes.draw do
  get 'users/edit' => 'user#edit'
  post 'users/update' => 'user#update'


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" }
  devise_scope :user do
    get  '/users/help' => 'sessions#help'
    post '/users/request_reset' => 'sessions#request_reset'
    get  '/users/reset_password' => 'sessions#reset_password'
    post '/users/send_reset_request' => 'sessions#send_reset_request'
  end

  get '/sign_up/ajaxEmailAlreadyExists' => 'sign_up#check_if_email_exists'

  resources :welcome
  resources :my_captures
  resources :marinas, except: [:show, :edit, :index]
  resources :tags
  resources :volunteer_hours
  resources :species, except: [:show, :edit]
  resources :sign_up
  resources :about
  resources :how_to_guide
  resources :contact_us

  resources :non_registered_captures

  scope 'api' do
    get '/capture_map_data' => 'api#capture_map_data'
    get '/photos' => 'api#get_photos'
    get '/tag_history' => 'my_captures#get_captures'
    get '/check_duplicate_capture' => 'api#check_duplicate_capture'
    get '/check_tag_exists' => 'api#check_tag_exists'
  end

  post '/marinas/search' => 'marinas#search'
  post '/marinas/clear_search' => 'marinas#clear_search'
  post '/species/search' => 'species#search'
  post '/species/clear_search' => 'species#clear_search'

  get '/thank_you' => 'common#thank_you'
  get '/species/image/:id/:image_name' => 'species#image'
  get '/check_captures' => 'my_captures#check_dup_caps'
  get '/draft_captures' => 'my_captures#draft_capture_index'
  post '/draft_captures_search' => 'my_captures#draft_capture_search'
  get '/draft_captures_search' => 'my_captures#draft_capture_search'
  get '/dashboard' => 'dashboards#index'

  post '/my_captures/:id' => 'my_captures#update'
  post '/my_captures/change_draft_capture_should_save/:id' => 'my_captures#change_draft_capture_should_save'
  get '/my_captures_report' => 'my_captures#get_capture_report'
  post '/my_captures_search' => 'my_captures#search'
  get '/my_captures_search' => 'my_captures#search'

  post '/contact_us/site_feedback' => 'contact_us#site_feedback'

  get '/faq' => 'faq#index'
  get '/privacy_policy' => 'privacy_policy#index'

  root :to => 'welcome#index'

end

app/views/nav/_primary.html.erb
<div id="primaryNav">
  <a href="<%= my_captures_path %>" class="<%=  (params[:came_from] == 'what') ? 'navTagger' : 'navTaggerHighlight' %>">I'm a tagger!</a>
  <a href="<%= new_sign_up_path %>" class="navStart">I'd like to start tagging</a>
  <a href="<%= about_index_path %>" class="<%= (params[:came_from] == 'what') ? 'navWhatIsHighlight' : 'navWhatIs' %>">What is tagging anyway?</a>
</div>

app/views/nav/_primary_about.html.erb
<div id="primaryNav">
  <a href="<%= my_captures_path %>" class="navTagger">I'm a tagger!</a>
  <a href="<%= new_sign_up_path %>" class="navStart">I'd like to start tagging</a>
  <a href="<%= about_index_path %>" class="<%=  params[:came_from] == 'what' ? 'navWhatIsHighlight' : 'navWhatIsHighlight' %>">What is tagging anyway?</a>
</div>

app/views/nav/_primary_sign_up.html.erb
<div id="primaryNav">
  <a href="<%= my_captures_path %>" class="navTagger">I'm a tagger!</a>
  <a href="<%= new_sign_up_path %>" class="navStartHighlight">I'd like to start tagging</a>
  <a href="<%= about_index_path %>" class="<%=  params[:came_from] == 'what' ? 'navWhatIsHighlight' : 'navWhatIs' %>">What is tagging anyway?</a>
</div>

app/views/nav/_signin.html.erb
<div id="subNav">
  <ul class="stripped">
    <li><a href="<%= dashboard_path %>">My Dashboard</a></li>
    <li><a href="<%= my_captures_path %>">My Captures</a></li>

    <% if has_pending_captures? %>
        <li><a href="<%= draft_captures_path %>">My Pending Captures</a></li>
    <% end %>

    <li><a href="<%= volunteer_hours_path %>">Enter Capture</a></li>
    <li><a href="<%= new_tag_path %>">Order Tags</a></li>
    <li><a href="<%= about_index_path %>">About</a></li>
    <li><a href="<%= how_to_guide_index_path %>">How-To</a></li>

    <!--<li><a href="<%= marinas_path %>">Find a Spot</a></li>-->

    <!--<li><a href="<%= species_index_path %>">Common Fish</a></li>-->
    <!--<li class="last"><a href="<%= species_index_path(:target => true) %>">Target Fish</a></li>-->
    <li><a href="<%= contact_us_path %>">Contact Us</a></li>
    <% if current_user %>
      <li><a href="<%= users_edit_path %>">Account Settings</a></li>
    <% end %>
    <li><a href="<%= faq_path %>">FAQ</a></li>
    <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
  </ul>

  <%=  button_to "Log Out", destroy_user_session_path, :method => :delete, :id => 'session-button' unless current_user.nil? %>
</div>

app/views/nav/_signup.html.erb
<div id="subNav">
  <ul class="stripped">
    <li class='last'><a href="<%= about_index_path%>">About Tagging</a></li>
    <!--<li class='last'><a href="#">Sign-up</a></li>-->
    <!-- Don't need this for now
    <li class="last"><a href="#">Events</a></li>
    -->
  </ul>

  <% if session[:auth_token].nil? %>
      <%=  button_to "Log In", {:controller => :sessions, :action => 'new'}, :method => :get, :id => 'session-button' %>
  <% else %>
      <%=  button_to "Log Out", {:controller => :sessions, :action => 'destroy', :id => 0}, :method => :delete, :id => 'session-button'%>
  <% end %>
</div>

app/views/nav/_wat.html.erb
<div id="subNav">
  <ul class="stripped">
    <li><a href="<%= about_index_path %>">About</a></li>
    <!-- Don't need this for now
    <li><a href="#">News</a></li>
    -->
    <!--<li><a href="#">Licensing</a></li>-->
    <!--<li><a href="<%= species_index_path :came_from => "what" %>">Common Fish</a></li>-->
    <!--<li><a href="<%= species_index_path :target => true, :came_from => "what" %>">Target Fish</a></li>-->
    <!--<li><a href="<%= marinas_path :came_from => "what" %>">Find a Spot</a></li>-->
    <li class="last"><a href="<%= how_to_guide_index_path :came_from => "what" %>">How To</a></li>
    <li><a href="<%= privacy_policy_path :came_from => "what" %>">Privacy Policy</a></li>
  </ul>

  <%=  button_to "Log Out", destroy_user_session_path, :method => :delete, :id => 'session-button' unless current_user.nil? %>
</div>